from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import os
import tempfile
import tomllib

from .errors import ManifestError
from .semver import Version


@dataclass(frozen=True)
class LockedPackage:
    name: str
    version: Version
    checksum: str
    deps: tuple[str, ...] = ()
    url: str | None = None


@dataclass
class Lockfile:
    packages: dict[str, LockedPackage] = field(default_factory=dict)
    version: int = 1


def load_lockfile(path: str | Path = "emerald.lock") -> Lockfile:
    path = Path(path)
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ManifestError(f"lockfile not found: {path}", "E_LOCK_NOT_FOUND", str(path)) from exc
    except tomllib.TOMLDecodeError as exc:
        raise ManifestError(f"invalid lockfile TOML: {exc}", "E_LOCK_TOML", str(path)) from exc
    if data.get("version") != 1:
        raise ManifestError(f"unsupported lockfile version `{data.get('version')}`", "E_LOCK_VERSION", str(path))
    result = {}
    for item in data.get("package", []):
        try:
            pkg = LockedPackage(item["name"], Version.parse(item["version"]), item["checksum"],
                                tuple(sorted(item.get("deps", []))), item.get("url"))
        except (KeyError, TypeError, ValueError) as exc:
            raise ManifestError(f"invalid lockfile package: {exc}", "E_LOCK_PACKAGE", str(path)) from exc
        if pkg.name in result:
            raise ManifestError(f"duplicate locked package `{pkg.name}`", "E_LOCK_PACKAGE", str(path))
        result[pkg.name] = pkg
    return Lockfile(result)


def dumps(lockfile: Lockfile) -> str:
    lines = ["# Generated by pme. Do not edit.", "version = 1", ""]
    for pkg in sorted(lockfile.packages.values(), key=lambda x: x.name):
        lines.extend(["[[package]]", f'name = "{pkg.name}"', f'version = "{pkg.version}"',
                      f'checksum = "{pkg.checksum}"'])
        deps = ", ".join(f'"{name}"' for name in sorted(pkg.deps))
        lines.append(f"deps = [{deps}]")
        if pkg.url is not None:
            escaped = pkg.url.replace('\\', '\\\\').replace('"', '\\"')
            lines.append(f'url = "{escaped}"')
        lines.append("")
    return "\n".join(lines)


def write_lockfile(lockfile: Lockfile, path: str | Path = "emerald.lock") -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(dumps(lockfile))
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
